SCREEN_PIXEL_WIDTH = 1024
SCREEN_PIXEL_HEIGHT = 768
PIXELS_PER_METER = 40.0 # [p/m]
SCREEN_REAL_WIDTH = SCREEN_PIXEL_WIDTH / PIXELS_PER_METER # [m]
SCREEN_REAL_HEIGHT = SCREEN_PIXEL_HEIGHT / PIXELS_PER_METER # [m]

GRAVITY = (0,-10) # [m s^-2]
AIR_RESISTANCE = 0.1 
FRICTION = 0.2
FPS = 60 # [s^-1]
DENSITY = 0.4

MAX_WALK_SPEED = 1 # [m s^-1]