SCREEN_PIXEL_WIDTH = 1024
SCREEN_PIXEL_HEIGHT = 768
#SCREEN_REAL_WIDTH = 25.6 # In meters
#SCREEN_REAL_HEIGHT = 1 # In meters
PIXELS_PER_METER = 40.0 # [p/m]
SCREEN_REAL_WIDTH = SCREEN_PIXEL_WIDTH / PIXELS_PER_METER
SCREEN_REAL_HEIGHT = SCREEN_PIXEL_HEIGHT / PIXELS_PER_METER

GRAVITY = (0,-10)
AIR_RESISTANCE = 0.1
FRICTION = 0.2
FPS = 60

MAX_WALK_SPEED = 1
