SCREEN_PIXEL_WIDTH = 1024
SCREEN_PIXEL_HEIGHT = 768
SCREEN_REAL_WIDTH = 10 # In meters
SCREEN_REAL_HEIGHT = 10 # In meters
PIXELS_PER_METER = 40.0 # [p/m]

GRAVITY = (0,-10)
FPS = 60

MAX_WALK_SPEED = 1
