PIXELS_PER_METER = 40

SCREEN_PIXEL_WIDTH = 1024
SCREEN_PIXEL_HEIGHT = 768
SCREEN_REAL_WIDTH = SCREEN_PIXEL_WIDTH / PIXELS_PER_METER
SCREEN_REAL_HEIGHT = SCREEN_PIXEL_HEIGHT / PIXELS_PER_METER

GRAVITY = (0,-10) # [m s^-2]
AIR_RESISTANCE = 0.1 
FRICTION = 0.2
FPS = 60 # [s^-1]
DENSITY = 0.4

FRAMERATE = 30 # [s^-1]
MAX_WALK_SPEED = 3 # [m s^-1]